"use client";
import { useState } from "react";

type Question={id:string;prompt:string;answer_outline:string;difficulty:number};
type Kit={questions:Question[];schedule:{days_available:number;days:{day:number;focus:string;question_ids:string[];minutes:number}[]};role:{requirements:{id:string;text:string;priority:string}[]};coverage:{uncovered_requirement_ids:string[]}};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000";

export default function Home(){
 const [kitId,setKitId]=useState(""); const [kit,setKit]=useState<Kit|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch(API+"/api/kits/"+encodeURIComponent(kitId));const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Failed to load kit");setKit(d.kit)}catch(e){setError(e instanceof Error?e.message:"Failed to load kit")}finally{setLoading(false)}}
 async function edit(q:Question,field:"prompt"|"answer_outline",value:string){if(!kit)return;setLoading(true);setError("");try{const r=await fetch(API+"/api/kits/"+encodeURIComponent(kitId),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"edit_question",question_id:q.id,[field]:value})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Edit failed");setKit(d.kit)}catch(e){setError(e instanceof Error?e.message:"Edit failed")}finally{setLoading(false)}}
 async function remove(id:string){if(!kit)return;setLoading(true);try{const r=await fetch(API+"/api/kits/"+encodeURIComponent(kitId),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"delete_question",question_id:id})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Delete failed");setKit(d.kit)}catch(e){setError(e instanceof Error?e.message:"Delete failed")}finally{setLoading(false)}}
 return <main><section className="shell"><h1>AI Interview Prep Kit</h1><p className="muted">Open and edit a generated interview kit.</p><div className="toolbar"><input aria-label="Kit ID" placeholder="kit_..." value={kitId} onChange={e=>setKitId(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load} disabled={!kitId||loading}>{loading?"Loading...":"Open kit"}</button></div>{error&&<div role="alert" className="error">{error}</div>}{kit&&<><div className="card"><h2>Requirements</h2>{kit.role.requirements.map(r=><div key={r.id}><strong>{r.priority}</strong> — {r.text}</div>)}</div><div className="card"><h2>Questions</h2>{kit.questions.map(q=><article key={q.id} className="question"><label>Question<textarea value={q.prompt} onChange={e=>edit(q,"prompt",e.target.value)}/></label><label>Answer outline<textarea value={q.answer_outline} onChange={e=>edit(q,"answer_outline",e.target.value)}/></label><button className="danger" onClick={()=>remove(q.id)}>Delete</button></article>)}</div><div className="card"><h2>Schedule</h2>{kit.schedule.days.map(d=><div className="day" key={d.day}><strong>Day {d.day}</strong><span>{d.focus}</span><span>{d.question_ids.length} questions · {d.minutes} min</span></div>)}</div></>}</section></main>
}
